# Build QuickToggle.apk (gradle-free): aapt2 link (manifest + res) -> javac -> d8 -> add dex -> zipalign -> sign.
$ErrorActionPreference = "Continue"

$SDK  = "$env:LOCALAPPDATA\Android\Sdk"
$BT   = "$SDK\build-tools\35.0.0"
$AJAR = "$SDK\platforms\android-34\android.jar"
$JDK  = "C:\Program Files\Java\jdk-21"
$env:JAVA_HOME = $JDK
$env:PATH = "$JDK\bin;" + $env:PATH

$PROJ  = $PSScriptRoot
$BUILD = Join-Path $PROJ "build"
$KS    = "C:\Users\lm\projects\dji\drone-plan\android\debug.keystore"

function Die($m){ Write-Host "BUILD FAILED: $m" -ForegroundColor Red; exit 1 }

New-Item -ItemType Directory -Force $BUILD | Out-Null
if (Test-Path "$BUILD\classes") { Remove-Item -Recurse -Force "$BUILD\classes" }
New-Item -ItemType Directory -Force "$BUILD\classes" | Out-Null

Write-Host "== aapt2 compile (res) =="
& "$BT\aapt2.exe" compile --dir "$PROJ\res" -o "$BUILD\res.zip"
if ($LASTEXITCODE -ne 0) { Die "aapt2 compile" }

Write-Host "== aapt2 link (manifest + res + assets) =="
$assetArgs = @()
if (Test-Path "$PROJ\assets") { $assetArgs = @("-A", "$PROJ\assets") }
& "$BT\aapt2.exe" link -I $AJAR --manifest "$PROJ\AndroidManifest.xml" "$BUILD\res.zip" @assetArgs `
  -o "$BUILD\app.unsigned.apk" --min-sdk-version 24 --target-sdk-version 30 `
  --java "$BUILD\gen"
if ($LASTEXITCODE -ne 0) { Die "aapt2 link" }

Write-Host "== BuildStamp =="
# Версия и время сборки, вкомпилированные в APK: страница «О программе» показывает их
# пользователю, а локальная проверка возраста сборки предупреждает, что APK устарел.
[xml]$mf = Get-Content "$PROJ\AndroidManifest.xml"
$verName = $mf.manifest.versionName
$verCode = $mf.manifest.versionCode
$gitRev  = (& git -C $PROJ rev-parse --short HEAD 2>$null)
if ([string]::IsNullOrWhiteSpace($gitRev)) { $gitRev = "nogit" }
$builtMs = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
$stampDir = "$BUILD\gen\com\djiquick"
New-Item -ItemType Directory -Force $stampDir | Out-Null
$stampSrc = @"
package com.djiquick;
/** Generated by build.ps1 - do not edit. */
public final class BuildStamp {
    public static final String NAME = "$verName";
    public static final int    CODE = $verCode;
    public static final String GIT  = "$gitRev";
    public static final long   BUILT_MS = ${builtMs}L;
    private BuildStamp() {}
}
"@
# WriteAllText с UTF8Encoding(`$false) — без BOM: Out-File -Encoding utf8 в PS 5.1 его добавляет,
# и javac падает на "illegal character: '﻿'".
[IO.File]::WriteAllText("$stampDir\BuildStamp.java", $stampSrc, (New-Object Text.UTF8Encoding $false))

Write-Host "== javac =="
$srcs = Get-ChildItem -Recurse "$PROJ\src","$BUILD\gen" -Filter *.java | ForEach-Object { $_.FullName }
& "$JDK\bin\javac.exe" --release 11 -classpath $AJAR -d "$BUILD\classes" $srcs 2>&1 |
  Where-Object { $_ -notmatch 'bootstrap class path|obsolete|To suppress|warning: \[options\]|warnings?$|deprecat' }
if ($LASTEXITCODE -ne 0) { Die "javac" }

Write-Host "== d8 =="
$classes = Get-ChildItem -Recurse "$BUILD\classes" -Filter *.class | ForEach-Object { $_.FullName }
& "$BT\d8.bat" --release --min-api 24 --lib $AJAR --output $BUILD $classes
if ($LASTEXITCODE -ne 0) { Die "d8" }

Write-Host "== add classes.dex =="
Push-Location $BUILD
& "$BT\aapt.exe" add "app.unsigned.apk" "classes.dex" | Out-Null
Pop-Location
if ($LASTEXITCODE -ne 0) { Die "aapt add" }

Write-Host "== zipalign + apksigner =="
& "$BT\zipalign.exe" -f -p 4 "$BUILD\app.unsigned.apk" "$BUILD\app.aligned.apk"
if ($LASTEXITCODE -ne 0) { Die "zipalign" }
& "$BT\apksigner.bat" sign --ks $KS --ks-pass pass:android --key-pass pass:android --ks-key-alias androiddebugkey --out "$BUILD\QuickToggle.apk" "$BUILD\app.aligned.apk"
if ($LASTEXITCODE -ne 0) { Die "apksigner" }

$sz = [math]::Round((Get-Item "$BUILD\QuickToggle.apk").Length/1KB,0)
Write-Host ("RESULT: " + (Join-Path $BUILD "QuickToggle.apk") + "  ($sz KB)  version $verName ($verCode) git $gitRev") -ForegroundColor Green
